// Comprehensive team → schedule/watch & tickets URL map
// Covers NBA, WNBA, NFL, MLB, MLS, NWSL, NHL, and major NCAA D1 programs

export interface TeamLinks {
  watch: string;
  tickets: string;
}

const TEAM_LINKS: Record<string, TeamLinks> = {
  // === NBA ===
  "Lakers": { watch: "https://www.nba.com/lakers/schedule", tickets: "https://www.nba.com/lakers/tickets" },
  "Clippers": { watch: "https://www.nba.com/clippers/schedule", tickets: "https://www.nba.com/clippers/tickets" },
  "Warriors": { watch: "https://www.nba.com/warriors/schedule", tickets: "https://www.nba.com/warriors/tickets" },
  "Celtics": { watch: "https://www.nba.com/celtics/schedule", tickets: "https://www.nba.com/celtics/tickets" },
  "Knicks": { watch: "https://www.nba.com/knicks/schedule", tickets: "https://www.nba.com/knicks/tickets" },
  "Nets": { watch: "https://www.nba.com/nets/schedule", tickets: "https://www.nba.com/nets/tickets" },
  "76ers": { watch: "https://www.nba.com/sixers/schedule", tickets: "https://www.nba.com/sixers/tickets" },
  "Bucks": { watch: "https://www.nba.com/bucks/schedule", tickets: "https://www.nba.com/bucks/tickets" },
  "Heat": { watch: "https://www.nba.com/heat/schedule", tickets: "https://www.nba.com/heat/tickets" },
  "Bulls": { watch: "https://www.nba.com/bulls/schedule", tickets: "https://www.nba.com/bulls/tickets" },
  "Suns": { watch: "https://www.nba.com/suns/schedule", tickets: "https://www.nba.com/suns/tickets" },
  "Mavericks": { watch: "https://www.nba.com/mavericks/schedule", tickets: "https://www.nba.com/mavericks/tickets" },
  "Nuggets": { watch: "https://www.nba.com/nuggets/schedule", tickets: "https://www.nba.com/nuggets/tickets" },
  "Thunder": { watch: "https://www.nba.com/thunder/schedule", tickets: "https://www.nba.com/thunder/tickets" },
  "Timberwolves": { watch: "https://www.nba.com/timberwolves/schedule", tickets: "https://www.nba.com/timberwolves/tickets" },
  "Kings": { watch: "https://www.nba.com/kings/schedule", tickets: "https://www.nba.com/kings/tickets" },
  "Grizzlies": { watch: "https://www.nba.com/grizzlies/schedule", tickets: "https://www.nba.com/grizzlies/tickets" },
  "Pelicans": { watch: "https://www.nba.com/pelicans/schedule", tickets: "https://www.nba.com/pelicans/tickets" },
  "Hawks": { watch: "https://www.nba.com/hawks/schedule", tickets: "https://www.nba.com/hawks/tickets" },
  "Raptors": { watch: "https://www.nba.com/raptors/schedule", tickets: "https://www.nba.com/raptors/tickets" },
  "Cavaliers": { watch: "https://www.nba.com/cavaliers/schedule", tickets: "https://www.nba.com/cavaliers/tickets" },
  "Pacers": { watch: "https://www.nba.com/pacers/schedule", tickets: "https://www.nba.com/pacers/tickets" },
  "Magic": { watch: "https://www.nba.com/magic/schedule", tickets: "https://www.nba.com/magic/tickets" },
  "Pistons": { watch: "https://www.nba.com/pistons/schedule", tickets: "https://www.nba.com/pistons/tickets" },
  "Hornets": { watch: "https://www.nba.com/hornets/schedule", tickets: "https://www.nba.com/hornets/tickets" },
  "Wizards": { watch: "https://www.nba.com/wizards/schedule", tickets: "https://www.nba.com/wizards/tickets" },
  "Trail Blazers": { watch: "https://www.nba.com/blazers/schedule", tickets: "https://www.nba.com/blazers/tickets" },
  "Jazz": { watch: "https://www.nba.com/jazz/schedule", tickets: "https://www.nba.com/jazz/tickets" },
  "Spurs": { watch: "https://www.nba.com/spurs/schedule", tickets: "https://www.nba.com/spurs/tickets" },
  "Rockets": { watch: "https://www.nba.com/rockets/schedule", tickets: "https://www.nba.com/rockets/tickets" },

  // === WNBA ===
  "Sparks": { watch: "https://sparks.wnba.com/schedule", tickets: "https://sparks.wnba.com/tickets" },
  "Aces": { watch: "https://aces.wnba.com/schedule", tickets: "https://aces.wnba.com/tickets" },
  "Liberty": { watch: "https://liberty.wnba.com/schedule", tickets: "https://liberty.wnba.com/tickets" },
  "Storm": { watch: "https://storm.wnba.com/schedule", tickets: "https://storm.wnba.com/tickets" },
  "Sky": { watch: "https://sky.wnba.com/schedule", tickets: "https://sky.wnba.com/tickets" },
  "Mercury": { watch: "https://mercury.wnba.com/schedule", tickets: "https://mercury.wnba.com/tickets" },
  "Fever": { watch: "https://fever.wnba.com/schedule", tickets: "https://fever.wnba.com/tickets" },
  "Mystics": { watch: "https://mystics.wnba.com/schedule", tickets: "https://mystics.wnba.com/tickets" },
  "Sun": { watch: "https://sun.wnba.com/schedule", tickets: "https://sun.wnba.com/tickets" },
  "Lynx": { watch: "https://lynx.wnba.com/schedule", tickets: "https://lynx.wnba.com/tickets" },
  "Dream": { watch: "https://dream.wnba.com/schedule", tickets: "https://dream.wnba.com/tickets" },
  "Wings": { watch: "https://wings.wnba.com/schedule", tickets: "https://wings.wnba.com/tickets" },

  // === NFL ===
  "Rams": { watch: "https://www.therams.com/schedule", tickets: "https://www.therams.com/tickets" },
  "Chargers": { watch: "https://www.chargers.com/schedule", tickets: "https://www.chargers.com/tickets" },
  "49ers": { watch: "https://www.49ers.com/schedule", tickets: "https://www.49ers.com/tickets" },
  "Chiefs": { watch: "https://www.chiefs.com/schedule", tickets: "https://www.chiefs.com/tickets" },
  "Eagles": { watch: "https://www.philadelphiaeagles.com/schedule", tickets: "https://www.philadelphiaeagles.com/tickets" },
  "Cowboys": { watch: "https://www.dallascowboys.com/schedule", tickets: "https://www.dallascowboys.com/tickets" },
  "Packers": { watch: "https://www.packers.com/schedule", tickets: "https://www.packers.com/tickets" },
  "Bills": { watch: "https://www.buffalobills.com/schedule", tickets: "https://www.buffalobills.com/tickets" },
  "Ravens": { watch: "https://www.baltimoreravens.com/schedule", tickets: "https://www.baltimoreravens.com/tickets" },
  "Dolphins": { watch: "https://www.miamidolphins.com/schedule", tickets: "https://www.miamidolphins.com/tickets" },
  "Lions": { watch: "https://www.detroitlions.com/schedule", tickets: "https://www.detroitlions.com/tickets" },
  "Seahawks": { watch: "https://www.seahawks.com/schedule", tickets: "https://www.seahawks.com/tickets" },
  "Steelers": { watch: "https://www.steelers.com/schedule", tickets: "https://www.steelers.com/tickets" },
  "Bears": { watch: "https://www.chicagobears.com/schedule", tickets: "https://www.chicagobears.com/tickets" },
  "Raiders": { watch: "https://www.raiders.com/schedule", tickets: "https://www.raiders.com/tickets" },
  "Broncos": { watch: "https://www.denverbroncos.com/schedule", tickets: "https://www.denverbroncos.com/tickets" },
  "Vikings": { watch: "https://www.vikings.com/schedule", tickets: "https://www.vikings.com/tickets" },
  "Giants": { watch: "https://www.giants.com/schedule", tickets: "https://www.giants.com/tickets" },
  "Jets": { watch: "https://www.newyorkjets.com/schedule", tickets: "https://www.newyorkjets.com/tickets" },
  "Saints": { watch: "https://www.neworleanssaints.com/schedule", tickets: "https://www.neworleanssaints.com/tickets" },
  "Patriots": { watch: "https://www.patriots.com/schedule", tickets: "https://www.patriots.com/tickets" },
  "Commanders": { watch: "https://www.commanders.com/schedule", tickets: "https://www.commanders.com/tickets" },
  "Cardinals": { watch: "https://www.azcardinals.com/schedule", tickets: "https://www.azcardinals.com/tickets" },
  "Bengals": { watch: "https://www.bengals.com/schedule", tickets: "https://www.bengals.com/tickets" },
  "Texans": { watch: "https://www.houstontexans.com/schedule", tickets: "https://www.houstontexans.com/tickets" },
  "Titans": { watch: "https://www.tennesseetitans.com/schedule", tickets: "https://www.tennesseetitans.com/tickets" },
  "Jaguars": { watch: "https://www.jaguars.com/schedule", tickets: "https://www.jaguars.com/tickets" },
  "Colts": { watch: "https://www.colts.com/schedule", tickets: "https://www.colts.com/tickets" },
  "Browns": { watch: "https://www.clevelandbrowns.com/schedule", tickets: "https://www.clevelandbrowns.com/tickets" },
  "Falcons": { watch: "https://www.atlantafalcons.com/schedule", tickets: "https://www.atlantafalcons.com/tickets" },
  "Panthers": { watch: "https://www.panthers.com/schedule", tickets: "https://www.panthers.com/tickets" },
  "Buccaneers": { watch: "https://www.buccaneers.com/schedule", tickets: "https://www.buccaneers.com/tickets" },

  // === MLB ===
  "Dodgers": { watch: "https://www.mlb.com/dodgers/schedule", tickets: "https://www.mlb.com/dodgers/tickets" },
  "Angels": { watch: "https://www.mlb.com/angels/schedule", tickets: "https://www.mlb.com/angels/tickets" },
  "Yankees": { watch: "https://www.mlb.com/yankees/schedule", tickets: "https://www.mlb.com/yankees/tickets" },
  "Mets": { watch: "https://www.mlb.com/mets/schedule", tickets: "https://www.mlb.com/mets/tickets" },
  "Red Sox": { watch: "https://www.mlb.com/redsox/schedule", tickets: "https://www.mlb.com/redsox/tickets" },
  "Cubs": { watch: "https://www.mlb.com/cubs/schedule", tickets: "https://www.mlb.com/cubs/tickets" },
  "Astros": { watch: "https://www.mlb.com/astros/schedule", tickets: "https://www.mlb.com/astros/tickets" },
  "Braves": { watch: "https://www.mlb.com/braves/schedule", tickets: "https://www.mlb.com/braves/tickets" },
  "Phillies": { watch: "https://www.mlb.com/phillies/schedule", tickets: "https://www.mlb.com/phillies/tickets" },
  "Padres": { watch: "https://www.mlb.com/padres/schedule", tickets: "https://www.mlb.com/padres/tickets" },
  "Giants (MLB)": { watch: "https://www.mlb.com/giants/schedule", tickets: "https://www.mlb.com/giants/tickets" },
  "SF Giants": { watch: "https://www.mlb.com/giants/schedule", tickets: "https://www.mlb.com/giants/tickets" },
  "Rangers": { watch: "https://www.mlb.com/rangers/schedule", tickets: "https://www.mlb.com/rangers/tickets" },
  "Mariners": { watch: "https://www.mlb.com/mariners/schedule", tickets: "https://www.mlb.com/mariners/tickets" },
  "Twins": { watch: "https://www.mlb.com/twins/schedule", tickets: "https://www.mlb.com/twins/tickets" },
  "White Sox": { watch: "https://www.mlb.com/whitesox/schedule", tickets: "https://www.mlb.com/whitesox/tickets" },
  "Guardians": { watch: "https://www.mlb.com/guardians/schedule", tickets: "https://www.mlb.com/guardians/tickets" },
  "Orioles": { watch: "https://www.mlb.com/orioles/schedule", tickets: "https://www.mlb.com/orioles/tickets" },
  "Rays": { watch: "https://www.mlb.com/rays/schedule", tickets: "https://www.mlb.com/rays/tickets" },
  "Blue Jays": { watch: "https://www.mlb.com/bluejays/schedule", tickets: "https://www.mlb.com/bluejays/tickets" },
  "Brewers": { watch: "https://www.mlb.com/brewers/schedule", tickets: "https://www.mlb.com/brewers/tickets" },
  "Reds": { watch: "https://www.mlb.com/reds/schedule", tickets: "https://www.mlb.com/reds/tickets" },
  "Pirates": { watch: "https://www.mlb.com/pirates/schedule", tickets: "https://www.mlb.com/pirates/tickets" },
  "Nationals": { watch: "https://www.mlb.com/nationals/schedule", tickets: "https://www.mlb.com/nationals/tickets" },
  "Marlins": { watch: "https://www.mlb.com/marlins/schedule", tickets: "https://www.mlb.com/marlins/tickets" },
  "Rockies": { watch: "https://www.mlb.com/rockies/schedule", tickets: "https://www.mlb.com/rockies/tickets" },
  "Royals": { watch: "https://www.mlb.com/royals/schedule", tickets: "https://www.mlb.com/royals/tickets" },
  "Tigers": { watch: "https://www.mlb.com/tigers/schedule", tickets: "https://www.mlb.com/tigers/tickets" },
  "Diamondbacks": { watch: "https://www.mlb.com/dbacks/schedule", tickets: "https://www.mlb.com/dbacks/tickets" },
  "Athletics": { watch: "https://www.mlb.com/athletics/schedule", tickets: "https://www.mlb.com/athletics/tickets" },

  // === MLS ===
  "LAFC": { watch: "https://www.lafc.com/schedule", tickets: "https://www.lafc.com/tickets" },
  "Galaxy": { watch: "https://www.lagalaxy.com/schedule", tickets: "https://www.lagalaxy.com/tickets" },
  "LA Galaxy": { watch: "https://www.lagalaxy.com/schedule", tickets: "https://www.lagalaxy.com/tickets" },
  "Inter Miami": { watch: "https://www.intermiamicf.com/schedule", tickets: "https://www.intermiamicf.com/tickets" },
  "NYCFC": { watch: "https://www.newyorkcityfc.com/schedule", tickets: "https://www.newyorkcityfc.com/tickets" },
  "Atlanta United": { watch: "https://www.atlutd.com/schedule", tickets: "https://www.atlutd.com/tickets" },
  "Seattle Sounders": { watch: "https://www.soundersfc.com/schedule", tickets: "https://www.soundersfc.com/tickets" },
  "Portland Timbers": { watch: "https://www.timbers.com/schedule", tickets: "https://www.timbers.com/tickets" },
  "Austin FC": { watch: "https://www.austinfc.com/schedule", tickets: "https://www.austinfc.com/tickets" },
  "San Diego FC": { watch: "https://www.sandiegofc.com/schedule", tickets: "https://www.sandiegofc.com/tickets" },

  // === NWSL ===
  "Angel City FC": { watch: "https://www.angelcity.com/schedule", tickets: "https://www.angelcity.com/tickets" },
  "ACFC": { watch: "https://www.angelcity.com/schedule", tickets: "https://www.angelcity.com/tickets" },
  "San Diego Wave": { watch: "https://www.sandiegowavefc.com/schedule", tickets: "https://www.sandiegowavefc.com/tickets" },
  "Wave": { watch: "https://www.sandiegowavefc.com/schedule", tickets: "https://www.sandiegowavefc.com/tickets" },
  "Portland Thorns": { watch: "https://www.timbers.com/thornsfc/schedule", tickets: "https://www.timbers.com/thornsfc/tickets" },
  "OL Reign": { watch: "https://www.olreign.com/schedule", tickets: "https://www.olreign.com/tickets" },
  "Gotham FC": { watch: "https://www.gothamfc.com/schedule", tickets: "https://www.gothamfc.com/tickets" },
  "Racing Louisville": { watch: "https://www.racingloufc.com/schedule", tickets: "https://www.racingloufc.com/tickets" },
  "KC Current": { watch: "https://www.kccurrent.com/schedule", tickets: "https://www.kccurrent.com/tickets" },
  "Chicago Red Stars": { watch: "https://www.chicagoredstars.com/schedule", tickets: "https://www.chicagoredstars.com/tickets" },

  // === NHL ===
  "LA Kings": { watch: "https://www.nhl.com/kings/schedule", tickets: "https://www.nhl.com/kings/tickets" },
  "Kings (NHL)": { watch: "https://www.nhl.com/kings/schedule", tickets: "https://www.nhl.com/kings/tickets" },
  "Ducks": { watch: "https://www.nhl.com/ducks/schedule", tickets: "https://www.nhl.com/ducks/tickets" },
  "Anaheim Ducks": { watch: "https://www.nhl.com/ducks/schedule", tickets: "https://www.nhl.com/ducks/tickets" },
  "Sharks": { watch: "https://www.nhl.com/sharks/schedule", tickets: "https://www.nhl.com/sharks/tickets" },
  "Bruins": { watch: "https://www.nhl.com/bruins/schedule", tickets: "https://www.nhl.com/bruins/tickets" },
  "Maple Leafs": { watch: "https://www.nhl.com/mapleleafs/schedule", tickets: "https://www.nhl.com/mapleleafs/tickets" },
  "Canadiens": { watch: "https://www.nhl.com/canadiens/schedule", tickets: "https://www.nhl.com/canadiens/tickets" },
  "Rangers (NHL)": { watch: "https://www.nhl.com/rangers/schedule", tickets: "https://www.nhl.com/rangers/tickets" },
  "Blackhawks": { watch: "https://www.nhl.com/blackhawks/schedule", tickets: "https://www.nhl.com/blackhawks/tickets" },
  "Penguins": { watch: "https://www.nhl.com/penguins/schedule", tickets: "https://www.nhl.com/penguins/tickets" },
  "Oilers": { watch: "https://www.nhl.com/oilers/schedule", tickets: "https://www.nhl.com/oilers/tickets" },
  "Red Wings": { watch: "https://www.nhl.com/redwings/schedule", tickets: "https://www.nhl.com/redwings/tickets" },
  "Avalanche": { watch: "https://www.nhl.com/avalanche/schedule", tickets: "https://www.nhl.com/avalanche/tickets" },
  "Lightning": { watch: "https://www.nhl.com/lightning/schedule", tickets: "https://www.nhl.com/lightning/tickets" },
  "Capitals": { watch: "https://www.nhl.com/capitals/schedule", tickets: "https://www.nhl.com/capitals/tickets" },
  "Golden Knights": { watch: "https://www.nhl.com/goldenknights/schedule", tickets: "https://www.nhl.com/goldenknights/tickets" },
  "Hurricanes": { watch: "https://www.nhl.com/hurricanes/schedule", tickets: "https://www.nhl.com/hurricanes/tickets" },
  "Kraken": { watch: "https://www.nhl.com/kraken/schedule", tickets: "https://www.nhl.com/kraken/tickets" },
  "Stars": { watch: "https://www.nhl.com/stars/schedule", tickets: "https://www.nhl.com/stars/tickets" },
  "Flyers": { watch: "https://www.nhl.com/flyers/schedule", tickets: "https://www.nhl.com/flyers/tickets" },
  "Predators": { watch: "https://www.nhl.com/predators/schedule", tickets: "https://www.nhl.com/predators/tickets" },
  "Wild": { watch: "https://www.nhl.com/wild/schedule", tickets: "https://www.nhl.com/wild/tickets" },
  "Blue Jackets": { watch: "https://www.nhl.com/bluejackets/schedule", tickets: "https://www.nhl.com/bluejackets/tickets" },
  "Islanders": { watch: "https://www.nhl.com/islanders/schedule", tickets: "https://www.nhl.com/islanders/tickets" },
  "Flames": { watch: "https://www.nhl.com/flames/schedule", tickets: "https://www.nhl.com/flames/tickets" },
  "Devils": { watch: "https://www.nhl.com/devils/schedule", tickets: "https://www.nhl.com/devils/tickets" },
  "Sabres": { watch: "https://www.nhl.com/sabres/schedule", tickets: "https://www.nhl.com/sabres/tickets" },
  "Senators": { watch: "https://www.nhl.com/senators/schedule", tickets: "https://www.nhl.com/senators/tickets" },
  "Jets (NHL)": { watch: "https://www.nhl.com/jets/schedule", tickets: "https://www.nhl.com/jets/tickets" },
  "Canucks": { watch: "https://www.nhl.com/canucks/schedule", tickets: "https://www.nhl.com/canucks/tickets" },
  "Coyotes": { watch: "https://www.nhl.com/coyotes/schedule", tickets: "https://www.nhl.com/coyotes/tickets" },

  // === NCAA D1 (LA area + major programs) ===
  "UCLA": { watch: "https://uclabruins.com/sports/schedule", tickets: "https://uclabruins.com/sports/tickets" },
  "UCLA Bruins": { watch: "https://uclabruins.com/sports/schedule", tickets: "https://uclabruins.com/sports/tickets" },
  "USC": { watch: "https://usctrojans.com/sports/schedule", tickets: "https://usctrojans.com/sports/tickets" },
  "USC Trojans": { watch: "https://usctrojans.com/sports/schedule", tickets: "https://usctrojans.com/sports/tickets" },
  "Pepperdine": { watch: "https://pepperdinewaves.com/sports/schedule", tickets: "https://pepperdinewaves.com/sports/tickets" },
  "LMU": { watch: "https://lmulions.com/sports/schedule", tickets: "https://lmulions.com/sports/tickets" },
  "CSUF": { watch: "https://fullertontitans.com/sports/schedule", tickets: "https://fullertontitans.com/sports/tickets" },
  "CSUN": { watch: "https://gomatadors.com/sports/schedule", tickets: "https://gomatadors.com/sports/tickets" },
  "LBSU": { watch: "https://longbeachstate.com/sports/schedule", tickets: "https://longbeachstate.com/sports/tickets" },
  "Long Beach State": { watch: "https://longbeachstate.com/sports/schedule", tickets: "https://longbeachstate.com/sports/tickets" },
  "UCI": { watch: "https://ucirvinesports.com/sports/schedule", tickets: "https://ucirvinesports.com/sports/tickets" },
  "UC Irvine": { watch: "https://ucirvinesports.com/sports/schedule", tickets: "https://ucirvinesports.com/sports/tickets" },
  "Alabama": { watch: "https://rolltide.com/sports/schedule", tickets: "https://rolltide.com/sports/tickets" },
  "Ohio State": { watch: "https://ohiostatebuckeyes.com/sports/schedule", tickets: "https://ohiostatebuckeyes.com/sports/tickets" },
  "Michigan": { watch: "https://mgoblue.com/sports/schedule", tickets: "https://mgoblue.com/sports/tickets" },
  "Texas": { watch: "https://texassports.com/sports/schedule", tickets: "https://texassports.com/sports/tickets" },
  "Georgia": { watch: "https://georgiadogs.com/sports/schedule", tickets: "https://georgiadogs.com/sports/tickets" },
  "Duke": { watch: "https://goduke.com/sports/schedule", tickets: "https://goduke.com/sports/tickets" },
  "UNC": { watch: "https://goheels.com/sports/schedule", tickets: "https://goheels.com/sports/tickets" },
  "Kentucky": { watch: "https://ukathletics.com/sports/schedule", tickets: "https://ukathletics.com/sports/tickets" },
  "Notre Dame": { watch: "https://und.com/sports/schedule", tickets: "https://und.com/sports/tickets" },
  "Oregon": { watch: "https://goducks.com/sports/schedule", tickets: "https://goducks.com/sports/tickets" },
  "Stanford": { watch: "https://gostanford.com/sports/schedule", tickets: "https://gostanford.com/sports/tickets" },
  "Florida": { watch: "https://floridagators.com/sports/schedule", tickets: "https://floridagators.com/sports/tickets" },
  "LSU": { watch: "https://lsusports.net/sports/schedule", tickets: "https://lsusports.net/sports/tickets" },
  "Michigan State": { watch: "https://msuspartans.com/sports/schedule", tickets: "https://msuspartans.com/sports/tickets" },
  "Penn State": { watch: "https://gopsusports.com/sports/schedule", tickets: "https://gopsusports.com/sports/tickets" },
  "Tennessee": { watch: "https://utsports.com/sports/schedule", tickets: "https://utsports.com/sports/tickets" },
  "Gonzaga": { watch: "https://gozags.com/sports/schedule", tickets: "https://gozags.com/sports/tickets" },
  "Kansas": { watch: "https://kuathletics.com/sports/schedule", tickets: "https://kuathletics.com/sports/tickets" },
  "Arizona": { watch: "https://arizonawildcats.com/sports/schedule", tickets: "https://arizonawildcats.com/sports/tickets" },
};

/**
 * Get the watch URL for a team. Falls back to Google search if not in the map.
 */
export function getTeamWatchUrl(teamName: string): string {
  const links = TEAM_LINKS[teamName];
  if (links) return links.watch;
  return `https://www.google.com/search?q=${encodeURIComponent(teamName + " live stream")}`;
}

/**
 * Get the tickets URL for a team. Falls back to Google search if not in the map.
 */
export function getTeamTicketsUrl(teamName: string): string {
  const links = TEAM_LINKS[teamName];
  if (links) return links.tickets;
  return `https://www.google.com/search?q=${encodeURIComponent(teamName + " tickets")}`;
}
