// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List upcoming Loverball events (watch parties, meetups) visible to the signed-in member, newest date first.",
  inputSchema: {
    limit: z.number().int().optional().describe("Max events to return (default 20)."),
    search: z.string().optional().describe("Optional text to match against event titles.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    let query = supabase.from("events").select("id,title,description,event_date,event_time,venue_name,location,city,visibility,image_url").gte("event_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)).order("event_date", { ascending: true }).limit(take);
    if (search?.trim()) query = query.ilike("title", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Fetch full details for one Loverball event by its id, plus the number of confirmed attendees.",
  inputSchema: { event_id: z2.string().describe("The event id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("events").select(
      "id,title,description,event_date,event_time,end_time,venue_name,location,location_map_url,city,event_type,sport_tags,event_tags,price,capacity,visibility,image_url,status"
    ).eq("id", event_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Event not found" }], isError: true };
    const { count } = await supabase.from("event_rsvps").select("id", { count: "exact", head: true }).eq("event_id", event_id).eq("status", "going");
    const event = { ...data, going_count: count ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(event) }],
      structuredContent: { event }
    };
  }
});

// src/lib/mcp/tools/list-my-rsvps.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_rsvps_default = defineTool3({
  name: "list_my_rsvps",
  title: "List my RSVPs",
  description: "List the signed-in member's RSVPs with the event title and date for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("event_rsvps").select("id,event_id,status,approval_status,attendance_status,created_at,events(title,event_date,venue_name)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rsvps: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/rsvp-to-event.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var rsvp_to_event_default = defineTool4({
  name: "rsvp_to_event",
  title: "RSVP to an event",
  description: "Create or update the signed-in member's RSVP for a Loverball event. Status is 'going' or 'not_going'.",
  inputSchema: {
    event_id: z3.string().describe("The event id (uuid)."),
    status: z3.enum(["going", "not_going"]).describe("RSVP status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const user_id = ctx.getUserId();
    const { data: existing } = await supabase.from("event_rsvps").select("id").eq("event_id", event_id).eq("user_id", user_id).maybeSingle();
    const { data, error } = existing ? await supabase.from("event_rsvps").update({ status }).eq("id", existing.id).select().maybeSingle() : await supabase.from("event_rsvps").insert({ event_id, user_id, status }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `RSVP saved: ${status}` }],
      structuredContent: { rsvp: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Fetch the signed-in member's Loverball profile: name, bio, favorite sports and teams, fan modes, and points.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "id,name,username,bio,pronouns,city,state,favorite_sports,favorite_teams,favorite_la_teams,fan_modes,fan_vibe,vibe_tags,total_points,current_streak,has_completed_onboarding"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Profile not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nfjavjfxgxrpvieinpdp";
var mcp_default = defineMcp({
  name: "loverball-hub",
  title: "loverball-hub",
  version: "0.1.0",
  instructions: "Tools for Loverball, a women's sports community app in LA. Browse upcoming events and watch parties, look up event details, manage the signed-in member's RSVPs, and read their profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, get_event_default, list_my_rsvps_default, rsvp_to_event_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
