import React from "react";
import { cn } from "@/lib/utils";

/**
 * <ResponsiveImage /> renders a <picture> with AVIF + WebP sources and a JPEG/PNG
 * fallback <img loading="lazy" decoding="async">. AVIF/WebP siblings are generated by scripts/optimize-images.mjs
 * and live alongside the original (e.g. hero.png → hero.avif + hero.webp).
 *
 * Always pass `width` and `height` (intrinsic pixel size) to prevent layout shift.
 * Use `priority` for above-the-fold images so they don't lazy-load.
 *
 * If the modern-format sibling doesn't exist for a given src, the browser will
 * silently fall through to the next <source> and finally to the <img loading="lazy" decoding="async"> tag.
 */
export type ResponsiveImageProps = {
  /** Path or imported asset URL of the original image. */
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Above-the-fold? Disables lazy-loading and bumps fetchpriority. */
  priority?: boolean;
  className?: string;
  /** Forwarded to <img loading="lazy" decoding="async">; useful for layout. */
  sizes?: string;
  /** Style overrides on the inner <img loading="lazy" decoding="async">. */
  style?: React.CSSProperties;
  /** Optional onLoad/onError handlers. */
  onLoad?: React.ReactEventHandler<HTMLImageElement>;
  onError?: React.ReactEventHandler<HTMLImageElement>;
};

function withExtension(src: string, ext: "avif" | "webp"): string {
  // Strip any query string, swap the extension, restore the query.
  const [pathPart, query = ""] = src.split("?");
  const swapped = pathPart.replace(/\.(png|jpg|jpeg)$/i, `.${ext}`);
  return query ? `${swapped}?${query}` : swapped;
}

export function ResponsiveImage({
  src,
  alt,
  width,
  height,
  priority = false,
  className,
  sizes,
  style,
  onLoad,
  onError,
}: ResponsiveImageProps) {
  const avifSrc = withExtension(src, "avif");
  const webpSrc = withExtension(src, "webp");
  const isRaster = /\.(png|jpg|jpeg)$/i.test(src.split("?")[0]);

  // For non-raster sources (svg, gif, already-webp) fall back to a plain <img loading="lazy" decoding="async">.
  if (!isRaster) {
    return (
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        // @ts-expect-error - fetchpriority is valid HTML, type lags
        fetchpriority={priority ? "high" : "auto"}
        className={className}
        sizes={sizes}
        style={style}
        onLoad={onLoad}
        onError={onError}
      />
    );
  }

  return (
    <picture>
      <source srcSet={avifSrc} type="image/avif" sizes={sizes} />
      <source srcSet={webpSrc} type="image/webp" sizes={sizes} />
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        // @ts-expect-error - fetchpriority is valid HTML, type lags
        fetchpriority={priority ? "high" : "auto"}
        className={cn(className)}
        sizes={sizes}
        style={style}
        onLoad={onLoad}
        onError={onError}
      />
    </picture>
  );
}

export default ResponsiveImage;
